#  docker-compose -f docker-compose_final.yml up --build -d
version: "3.8"

services:
  api_gateway:
    build: ./api_gateway
    container_name: api_gateway_service
    ports:
      - "6000:6000"
    depends_on:
      - rabbitmq

  auth_service:
    build: ./auth
    container_name: auth_service
    ports:
      - "6001:6001"
    env_file:
      - ./auth/.env
    depends_on:
      - rabbitmq

  patient_service:
    build: ./patient
    container_name: patient_service
    ports:
      - "6002:6002"
    env_file:
      - ./patient/.env
    depends_on:
      - rabbitmq

  staff_service:
    build: ./staff
    container_name: staff_service
    ports:
      - "6003:6003"
    env_file:
      - ./staff/.env
    depends_on:
      - rabbitmq

  appointment_service:
    build: ./appointment
    container_name: appointment_service
    ports:
      - "6004:6004"
    env_file:
      - ./appointment/.env
    depends_on:
      - rabbitmq

  lab_service:
    build: ./lab
    container_name: lab_service
    ports:
      - "6005:6005"
    env_file:
      - ./lab/.env
    depends_on:
      - rabbitmq

  pharmacy_service:
    build: ./pharmacy
    container_name: pharmacy_service
    ports:
      - "6006:6006"
    env_file:
      - ./pharmacy/.env
    depends_on:
      - rabbitmq

  medical_record_service:
    build: ./medical_record
    container_name: medical_record_service
    ports:
      - "6007:6007"
    env_file:
      - ./medical_record/.env
    depends_on:
      - rabbitmq

  notification_service:
    build: ./notification
    container_name: notification_service # Fixed: Now has predictable name
    ports:
      - "6008:6008"
    depends_on:
      - rabbitmq

  rabbitmq:
    image: rabbitmq:3-management
    container_name: hospital_rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672" # AMQP protocol
      - "15672:15672" # Management UI
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  rabbitmq_data:
